### ISSUE TITLE
effects implementation

### ISSUE THREAD

**Issue by hacker-h** [pilotak/docker-rpi-ws281x-mqtt#2]
Hi,
do you have an example on how to properly implement effects?
The readme refers to the `Knight Rider` effect, however I cannot find any implementation and my approaches to implement effects would require severe refactoring. Could you briefly explain the supposed way of implementation?

**Comment by pilotak** [comment]
Honestly effects are my wish and are on todo list but far bottom. Anyway if you want to submit a PR you more than welcome i don't mind refactoring i would probably have to make them too.

**Comment by hacker-h** [comment]
I did some work in the last days:
https://github.com/pilotak/docker-rpi-ws281x-mqtt/pull/3

Feel free to integrate what you like
